baseURL = 'https://dev.luanti.org/'
languageCode = 'en-us'
title = 'Developer Wiki'
theme = ['hugo-notice', 'hugo-book']
enableGitInfo = true

[params]
    BookTheme = 'auto'
    BookSection = '*'
    BookRepo = 'https://github.com/minetest/dev.luanti.org'
    BookEditPath = 'edit/master'
