baseURL = 'https://newdev.luanti.org/'
languageCode = 'en-us'
title = 'Developer Wiki'
theme = 'hugo-book'
enableGitInfo = true
DisablePathToLower = true

[params]
    BookTheme = 'auto'
    BookSection = '*'
    BookRepo = 'https://github.com/wsor4035/devwiki'
